//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskDetail
    {
        public int Id { get; set; }
        public Nullable<int> Parent_Id { get; set; }
        public string Task_Name { get; set; }
        public Nullable<int> Range { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
    }
}
